spring:
  datasource:
    url: jdbc:postgresql://185.246.66.164:5432/photo_world
    username: pw_admin
    password: pw_admin_123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

aws:
  endpointUrl: https://storage.yandexcloud.net
  accessKey: YCAJEhwOVaDfYFT1NypaMlH4G
  secretKey: YCO17rwbH3iHmhnpJMQRHvN6c-Jh3J3ITJ4gbPCg
  bucketName: photoworld-backet
  region: ru-central1

sendbird:
  appId: BA3B023F-C58B-4300-816F-498A9653B773
  apiToken: 4ead78524a8d6d1d9f6a2b8b75a676ab8818c967

server:
  port: 9090