spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/photo_world
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

aws:
  endpointUrl: https://storage.yandexcloud.net
  accessKey:
  secretKey:
  bucketName: photoworld-backet
  region: ru-central1

sendbird:
  appId: BA3B023F-C58B-4300-816F-498A9653B773
  apiToken:

server:
  port: 9090